version: "3"

services:
  monicahq:
    build: .
    image: monicahq/monicahq
    depends_on:
      - mysql
    ports:
      - 80:80
    env_file: .env
    networks:
      - database:
    volumes:
      - monica_data:/var/www/monica/storage

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    networks:
      - database:
    volumes:
      - monica_mysql:/var/lib/mysql

networks:
  database:

volumes:
  monica_data:
  monica_mysql:
